language: node_js
node_js:
  - "7"
env:
  - NODE_ENV=travis
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services:
  - mongodb
  - rabbitmq
  - docker
notifications:
  email:
      - alokadhao@gmail.com
install:
 - npm install
 - bash ./build/runUnitTest.sh
 - bash ./build/runContractTest.sh 
 - bash ./before_install_setup.sh
 - bash ./install_setup.sh
 - bash ./buildDockerImage.sh

before_install:
 - "source <(curl -H 'Authorization: token '$GIT_USER_TOKEN'' -L https://raw.githubusercontent.com/alokadhao20/testCI01/master/before_install_setup.sh)"

